openapi: 3.0.0
info:
  title: Folders API
  description: API documentation for Folders
  version: 0.1.0
  license:
    name: UNLICENSED
    url: NONE
servers:
  - url: NONE
    description: NONE
security:
  - basicAuth: []
paths:
  /folders:
    get:
      summary: Get the list of folders
      operationId: getFolders
      parameters:
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: An array of folders
          content:
            application/json:
              schema:
                type: object
                required:
                  - folders
                properties:
                  folders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Folder'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create a Folder
      operationId: createFolder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFolder'
      responses:
        '200':
          description: An array of random values
          content:
            application/json:
              schema:
                type: object
                required:
                  - folder
                properties:
                  folder:
                    $ref: '#/components/schemas/Folder'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /folders/{folderId}:
    get:
      summary: Return a specific folder
      operationId: getFolder
      parameters:
        - $ref: '#/components/parameters/folderId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                required:
                  - folder
                properties:
                  folder:
                    $ref: '#/components/schemas/Folder'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Update a Folder
      operationId: updateFolder
      parameters:
        - $ref: '#/components/parameters/folderId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFolder'
      responses:
        '200':
          description: An array of random values
          content:
            application/json:
              schema:
                type: object
                required:
                  - folder
                properties:
                  folder:
                    $ref: '#/components/schemas/Folder'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete a specific folder
      operationId: deleteFolder
      parameters:
        - $ref: '#/components/parameters/folderId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                required:
                  - deletedFolder
                properties:
                  deletedFolder:
                    $ref: '#/components/schemas/Folder'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    limit:
      name: limit
      in: query
      description: Limit the amount of items returned
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 100
    folderId:
      name: folderId
      in: path
      required: true
      description: The id of the folder to return
      schema:
        type: integer
  schemas:
    Folder:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    ErrorCodes:
      type: string
      enum:
        - UNKNOWN
    ErrorResponse:
      type: object
      required:
        - message
        - errorCodes
      properties:
        message:
          type: string
        errorCodes:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCodes'
    CreateFolder:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    UpdateFolder:
      type: object
      required:
        - name
      properties:
        name:
          type: string
  responses:
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
