fileId:
  name: fileId
  in: path
  required: true
  description: The id of the file to return
  schema:
    type: string
    format: uuid

limit:
  name: limit
  in: query
  description: Limit the amount of items returned
  required: true
  schema:
    type: integer
    format: int32
    minimum: 0
    maximum: 100
