# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

env:
  PORT: 3000
  DATABASE_URL: 'postgresql://root:${{secrets.db_password}}@localhost:3306/build_db'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    services:
      mydb:
        image: postgres:14.13
        env:
          POSTGRES_USER: build_user
          POSTGRES_DATABASE: build_db
          POSTGRES_PASSWORD: ${{ secrets.db_password }}
        ports:
          - 3306:3306
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run db:migrate
      - run: npm test
      - run: npm run build
