openapi: 3.0.0

info:
  title: Folders API
  description: API documentation for Folders
  version: 0.1.0
  license:
    name: UNLICENSED
    url: NONE

servers:
  - url: /
    description: Base API endpoint

# TODO update this from Basic to something else when auth is done
security:
  - basicAuth: []

paths:
  $ref: '../routes/docs/index.yaml'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

externalDocs:
  url: /docs
  description: Documentation for the API
